version: '3.7'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: app-db
    ports:
      - $DB_PORT:5432
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - app-volume:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  app-volume:

networks:
  app-network:
    driver: bridge
    name: app-network