version: '3.7'

services:
  api:
    build: .
    restart: unless-stopped
    container_name: app-node
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./src:/node-app/src
    networks:
      - app-network

  db:
    image: postgres
    restart: unless-stopped
    container_name: app-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - app-volume:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  app-volume:

networks:
  app-network:
    driver: bridge
    name: app-network